language:
  - cpp
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
before_script:
  - wget -qO- "https://cmake.org/files/v3.12/cmake-3.12.2-Linux-x86_64.tar.gz" | tar --strip-components=1 -xz -C ~/.local
script:
  - cmake -H. -Bbuild  -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cd build
  - cmake --build .
  - ./test/CAHRR_test
env:
  - BUILD_TYPE=DEBUG
  - BUILD_TYPE=RELEASE
